apiVersion: v1
kind: Service
metadata:
  name: sandstone-frontend
spec:
  type: NodePort             # Expose on each node
  selector:
    app: sandstone-frontend
  ports:
    - port: 80               # inside cluster
      targetPort: 80         # container port
      nodePort: 30080        # accessible from browser

