apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP               # Internal service only
  selector:
    app: postgres               # Connects pods with these labels
  ports:
    - port: 5432                # Service port
      targetPort: 5432          # Container port

