apiVersion: v1          # Kubernetes API group
kind: Secret            # Type of object: Secret
metadata:
  name: postgres-secret # Name of the secret (referenced later)
type: Opaque            # Generic secret (string â†’ base64)
data:
  password: cG9zdGdyZXM=   # base64("postgres")

